plugins = []
headers = []
redirects = []

[functions]

[functions."*"]

[build]
publish = "/Users/milky/.openclaw/workspace/mvp-deploy/mvp107-uuid-gen"
publishOrigin = "config"
commandOrigin = "ui"
base = "/Users/milky/.openclaw/workspace/mvp-deploy/mvp107-uuid-gen"

[build.environment]

[build.processing]

[build.processing.css]

[build.processing.html]

[build.processing.images]

[build.processing.js]

[build.services]