plugins = []
headers = []
redirects = []

[[redirect]]
from = "/*"
to = "/index.html"
status = 200.0

[functions]

[functions."*"]

[build]
publish = "/Users/milky/.openclaw/workspace/mvp-deploy/mvp109-base64"
publishOrigin = "config"
commandOrigin = "ui"
base = "/Users/milky/.openclaw/workspace/mvp-deploy/mvp109-base64"

[build.environment]

[build.processing]

[build.processing.css]

[build.processing.html]

[build.processing.images]

[build.processing.js]

[build.services]