redirectsOrigin = "config"
plugins = []
headers = []

[functions]

[functions."*"]

[build]
publish = "/Users/milky/.openclaw/workspace/mvp-deploy/mvp49-json-path"
publishOrigin = "config"
commandOrigin = "config"
base = "/Users/milky/.openclaw/workspace/mvp-deploy/mvp49-json-path"
command = "echo 'No build needed'"

[build.environment]

[build.processing]

[build.processing.css]

[build.processing.html]

[build.processing.images]

[build.processing.js]

[build.services]

[[redirects]]
from = "/*"
to = "/index.html"
status = 200.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]