plugins = []
headers = []
redirects = []

[dev]
command = ""
publish = "."

[functions]

[functions."*"]

[build]
publish = "/Users/milky/.openclaw/workspace/mvp-deploy/mvp95-sql-formatter"
publishOrigin = "config"
commandOrigin = "ui"
base = "/Users/milky/.openclaw/workspace/mvp-deploy/mvp95-sql-formatter"

[build.environment]

[build.processing]

[build.processing.css]

[build.processing.html]

[build.processing.images]

[build.processing.js]

[build.services]